### ISSUE TITLE
Include a top-level comment link in ping messages

### ISSUE THREAD

**Issue by jenbanim** [neoliberal/user_pinger#19]
Some Reddit platforms don't make it easy to navigate up comment trees (ie. no parent or permalink buttons). This makes it difficult to see other replies to the pinged comment, especially if the ping was left as a reply to the comment rather than put in the comment itself.

Including a link to the top-level comment will be helpful for those users.

**Comment by jan-polivka** [comment]
I'm guessing the best way to go about this is to post the parent link by default if it exists. I'm not sure if I'll be able to setup a dev environment as it looks a lot more complicated than just adjusting line 15 in service.py. So instead, I just played around with PRAW.

Anyway, here's an idea for lines ~315-321
```
            try:
                unsub_group_msg: str = ...
                unsub_all_msg: str = ...

                if 't_1' in comment.parent_id:
                    comment_parent = self.reddit.comment(comment.parent_id[3:])
                    parent_link_msg: str = f"[Click here to view the parent comment](https://www.reddit.com{str(comment_parent.permalink)}?context=1000)\n\n"
                else:
                    parent_link_msg: str = f""
                self.reddit.redditor(user).message(
                    subject=f"You've been pinged by /u/{comment.author} in group {group}",
                    message=f"[Click here to view the comment](https://www.reddit.com{str(comment.permalink)}?context=1000){parent_link_msg}\n\n---\n\n{unsub_group_msg}\n\n{unsub_all_msg}"
                )
```
What is added is the if-else decision point and then {parent_link_msg} in the message for the user. I can attempt to create a pull request, if approved.

It ain't much but it's honest work.

**Comment by jenbanim** [comment]
Thanks for this! I don't think I'm going to use this code directly, since I'm planning on switching to templating for the messages when I rewrite the bot, rather than f-strings within the python script, but I'm definitely going to use the ideas here

**Comment by jan-polivka** [comment]
Is the rewrite coming soon? This is a pretty small feature, so it seems to me like it would be a quick merge.

Also, let me know if there's anything else I can contribute to.

**Comment by jenbanim** [comment]
I've been putting this off way too long. I'm gonna try to bang this out tonight

**Comment by jenbanim** [comment]
Resolved in user_pinger_2 https://github.com/neoliberal/user_pinger_2
